#!/bin/bash
set -e

SAMPLE=${SAMPLE:-sample.nim}

# default port
PORT=${PORT:-6000}

if pgrep nimsuggest; then
  pkill -9 nimsuggest
fi

nimsuggest --verbosity:0 --port:$PORT "${SAMPLE}" &

sleep 1

nc -q 1 localhost $PORT < message > received/$FILE

# -Z : ignore trailing white spaces
diff -Z expected_tmp/$FILE received/$FILE
